[package]
name = "document-reader-for-pc"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
glib = "0.9.0"
gio = "0.9.0"
cairo = "0.9.0"
pango = "0.9.0"

[profile.release]
opt-level = 3